export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  NOT_FOUND = 'NOT_FOUND',
  NOT_FOUND_ID = 'NOT_FOUND_ID',
  SAVE_FAILED = 'SAVE_FAILED',
  UPDATE_FAILED = 'UPDATE_FAILED',
  DELETE_FAILED = 'DELETE_FAILED',
  CAN_NOT_LOGIN = 'CAN_NOT_LOGIN',
  FRESH_TOKEN_WRONG = 'FRESH_TOKEN_WRONG',
}

export enum HttpStatus {
  BAD_REQUEST = 400,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}
